title: "Solo by Allan Switzer"
baseurl: ""
url: ""
permalink: /:title/
collections:
  products:
    output: true
    sort_by: ["number", "letter"]

# Build settings
theme: minima
plugins:
  - jekyll-feed
